# Generated by Django 2.1.5 on 2019-01-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_task_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_image',
            new_name='image',
        ),
    ]
